### ISSUE TITLE
Initial position of robot is reset by traj_server

### ISSUE THREAD

**Issue by rubbishdq** [HKUST-Aerial-Robotics/FUEL#10]
See line 472 of traj_server.cpp. The initial position is reset by command from traj_server, making setting params in launch files meaningless.

**Comment by ZbyLGsc** [comment]
Yes it is a problem. Thanks for reporting it.

**Comment by ZbyLGsc** [comment]
Now the initial position fully depends on the params set in launch file. At the beginning of the exploration, traj_server utilizes the params to generate initialization motion.
