### ISSUE TITLE
Unable to catkin_make

### ISSUE THREAD

**Issue by timothymah** [HKUST-Aerial-Robotics/FUEL#16]
Hi, 

I tried to catkin_make this package but I am getting this error:
/usr/bin/ld: cannot find -ldw
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -ldw
collect2: error: ld returned 1 exit status
FUEL/fuel_planner/plan_manage/CMakeFiles/fast_planner_node.dir/build.make:575: recipe for target '/home/tim/fuel_ws/devel/lib/plan_manage/fast_planner_node' failed
make[2]: *** [/home/tim/fuel_ws/devel/lib/plan_manage/fast_planner_node] Error 1
FUEL/fuel_planner/plan_manage/CMakeFiles/traj_server.dir/build.make:500: recipe for target '/home/tim/fuel_ws/devel/lib/plan_manage/traj_server' failed
make[2]: *** [/home/tim/fuel_ws/devel/lib/plan_manage/traj_server] Error 1
CMakeFiles/Makefile2:5816: recipe for target 'FUEL/fuel_planner/plan_manage/CMakeFiles/fast_planner_node.dir/all' failed
make[1]: *** [FUEL/fuel_planner/plan_manage/CMakeFiles/fast_planner_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:5736: recipe for target 'FUEL/fuel_planner/plan_manage/CMakeFiles/traj_server.dir/all' failed
make[1]: *** [FUEL/fuel_planner/plan_manage/CMakeFiles/traj_server.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

Thanks!

**Comment by kjyothiswaroop** [comment]
Hey @timothymah  how did you solve the above issue?
