### ISSUE TITLE
Cannot open uav_simulator

### ISSUE THREAD

**Issue by itsng** [HKUST-Aerial-Robotics/FUEL#2]
Hi,

I cannot open the uav_simulator on github website.

`git clone https://github.com/HKUST-Aerial-Robotics/FUEL.git` will give an empty uav_simulator folder.

Can you help to solve it? Thanks!

**Comment by danigr99727** [comment]
Try to look into cloning git submodules? https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by itsng** [comment]
> Try to look into cloning git submodules? https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

Thank you for the information!

My git version is 2.17.1.

I tried `git clone --recurse-submodules https://github.com/HKUST-Aerial-Robotics/FUEL.git`, but also got an empty uav_simulator folder.

Then I tried `git submodule init`, it returned `fatal: No url found for submodule path 'uav_simulator' in .gitmodules`.

**Comment by ZbyLGsc** [comment]
@itsng Hi, thanks for reporting the issue. It should have been fixed.

**Comment by ZbyLGsc** [comment]
Thanks for reporting. The issue have been fixed.
